/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MbAmbulanceWlApp {
        "ambulanceId": string;
        "apiBase": string;
        /**
          * @default ""
         */
        "basePath": string;
    }
    interface MbAmbulanceWlEditor {
        "entryId": string;
    }
    interface MbAmbulanceWlList {
        "ambulanceId": string;
        "apiBase": string;
    }
}
export interface MbAmbulanceWlEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMbAmbulanceWlEditorElement;
}
export interface MbAmbulanceWlListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMbAmbulanceWlListElement;
}
declare global {
    interface HTMLMbAmbulanceWlAppElement extends Components.MbAmbulanceWlApp, HTMLStencilElement {
    }
    var HTMLMbAmbulanceWlAppElement: {
        prototype: HTMLMbAmbulanceWlAppElement;
        new (): HTMLMbAmbulanceWlAppElement;
    };
    interface HTMLMbAmbulanceWlEditorElementEventMap {
        "editor-closed": string;
    }
    interface HTMLMbAmbulanceWlEditorElement extends Components.MbAmbulanceWlEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMbAmbulanceWlEditorElementEventMap>(type: K, listener: (this: HTMLMbAmbulanceWlEditorElement, ev: MbAmbulanceWlEditorCustomEvent<HTMLMbAmbulanceWlEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMbAmbulanceWlEditorElementEventMap>(type: K, listener: (this: HTMLMbAmbulanceWlEditorElement, ev: MbAmbulanceWlEditorCustomEvent<HTMLMbAmbulanceWlEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMbAmbulanceWlEditorElement: {
        prototype: HTMLMbAmbulanceWlEditorElement;
        new (): HTMLMbAmbulanceWlEditorElement;
    };
    interface HTMLMbAmbulanceWlListElementEventMap {
        "entry-clicked": string;
    }
    interface HTMLMbAmbulanceWlListElement extends Components.MbAmbulanceWlList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMbAmbulanceWlListElementEventMap>(type: K, listener: (this: HTMLMbAmbulanceWlListElement, ev: MbAmbulanceWlListCustomEvent<HTMLMbAmbulanceWlListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMbAmbulanceWlListElementEventMap>(type: K, listener: (this: HTMLMbAmbulanceWlListElement, ev: MbAmbulanceWlListCustomEvent<HTMLMbAmbulanceWlListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMbAmbulanceWlListElement: {
        prototype: HTMLMbAmbulanceWlListElement;
        new (): HTMLMbAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "mb-ambulance-wl-app": HTMLMbAmbulanceWlAppElement;
        "mb-ambulance-wl-editor": HTMLMbAmbulanceWlEditorElement;
        "mb-ambulance-wl-list": HTMLMbAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface MbAmbulanceWlApp {
        "ambulanceId"?: string;
        "apiBase"?: string;
        /**
          * @default ""
         */
        "basePath"?: string;
    }
    interface MbAmbulanceWlEditor {
        "entryId"?: string;
        "onEditor-closed"?: (event: MbAmbulanceWlEditorCustomEvent<string>) => void;
    }
    interface MbAmbulanceWlList {
        "ambulanceId"?: string;
        "apiBase"?: string;
        "onEntry-clicked"?: (event: MbAmbulanceWlListCustomEvent<string>) => void;
    }

    interface MbAmbulanceWlAppAttributes {
        "basePath": string;
        "apiBase": string;
        "ambulanceId": string;
    }
    interface MbAmbulanceWlEditorAttributes {
        "entryId": string;
    }
    interface MbAmbulanceWlListAttributes {
        "apiBase": string;
        "ambulanceId": string;
    }

    interface IntrinsicElements {
        "mb-ambulance-wl-app": Omit<MbAmbulanceWlApp, keyof MbAmbulanceWlAppAttributes> & { [K in keyof MbAmbulanceWlApp & keyof MbAmbulanceWlAppAttributes]?: MbAmbulanceWlApp[K] } & { [K in keyof MbAmbulanceWlApp & keyof MbAmbulanceWlAppAttributes as `attr:${K}`]?: MbAmbulanceWlAppAttributes[K] } & { [K in keyof MbAmbulanceWlApp & keyof MbAmbulanceWlAppAttributes as `prop:${K}`]?: MbAmbulanceWlApp[K] };
        "mb-ambulance-wl-editor": Omit<MbAmbulanceWlEditor, keyof MbAmbulanceWlEditorAttributes> & { [K in keyof MbAmbulanceWlEditor & keyof MbAmbulanceWlEditorAttributes]?: MbAmbulanceWlEditor[K] } & { [K in keyof MbAmbulanceWlEditor & keyof MbAmbulanceWlEditorAttributes as `attr:${K}`]?: MbAmbulanceWlEditorAttributes[K] } & { [K in keyof MbAmbulanceWlEditor & keyof MbAmbulanceWlEditorAttributes as `prop:${K}`]?: MbAmbulanceWlEditor[K] };
        "mb-ambulance-wl-list": Omit<MbAmbulanceWlList, keyof MbAmbulanceWlListAttributes> & { [K in keyof MbAmbulanceWlList & keyof MbAmbulanceWlListAttributes]?: MbAmbulanceWlList[K] } & { [K in keyof MbAmbulanceWlList & keyof MbAmbulanceWlListAttributes as `attr:${K}`]?: MbAmbulanceWlListAttributes[K] } & { [K in keyof MbAmbulanceWlList & keyof MbAmbulanceWlListAttributes as `prop:${K}`]?: MbAmbulanceWlList[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mb-ambulance-wl-app": LocalJSX.IntrinsicElements["mb-ambulance-wl-app"] & JSXBase.HTMLAttributes<HTMLMbAmbulanceWlAppElement>;
            "mb-ambulance-wl-editor": LocalJSX.IntrinsicElements["mb-ambulance-wl-editor"] & JSXBase.HTMLAttributes<HTMLMbAmbulanceWlEditorElement>;
            "mb-ambulance-wl-list": LocalJSX.IntrinsicElements["mb-ambulance-wl-list"] & JSXBase.HTMLAttributes<HTMLMbAmbulanceWlListElement>;
        }
    }
}
